version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: plannerx
      POSTGRES_USER: plannerx
      POSTGRES_PASSWORD: plannerx_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plannerx"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.api
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://plannerx:plannerx_password@postgres:5432/plannerx
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data

volumes:
  postgres_data:
